### ISSUE TITLE
cmake-for-boost submodule is missing

### ISSUE THREAD

**Issue by blastmaster** [arangodb/fuerte#1]
Hi, 
when cloning fuerte with `--recursive` I encounter the following error:
`fatal: No url found for submodule path 'arango-cxx-driver/3rdParty/cmake-for-boost' in .gitmodules`.
When looking at `.gitmodules` there is also no submodule "cmake-for-boost".
This should not be a big issue and i was able to build fuerte when comment out [this line](https://github.com/arangodb/fuerte/blob/master/arango-cxx-driver/CMakeLists.txt#L27) in `arango-cxx-dirver/CMakeList.txt`.

**Comment by ObiWahn** [comment]
Hi,
the repository is added and you should clone fuerte and then init and update the submodules. If you clone recursively you end up downloading all boost libraries.
