### ISSUE TITLE
Missing connection options

### ISSUE THREAD

**Issue by sandrokeil** [arangodb/fuerte#10]
There are many [connection options](https://github.com/arangodb/arangodb-php/blob/devel/lib/ArangoDBClient/ConnectionOptions.php) which are not supported (may depend on connection protocol) at the moment. Any plans to add the missing options?

**Comment by graetzer** [comment]
This is intended to be a low-level driver, basically only providing the transport layer to the ArangoDB server. Most of these options are only useful for a higher level driver
