### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by EEMaddy** [arangodb/fuerte#13]
I'm trying to build fuerte in centos7 environment and i get the below error.

CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_C_COMPILE_OBJECT

If i edit CMakeList.txt -> "project(fuerte CXX)" to "project(fuerte CXX C)" then it builds successfully. Please advise if I'm doing it correctly.

**Comment by fceller** [comment]
@EEMaddy can you tell me which version of cmake you are using? Thx

**Comment by AlexLuya** [comment]
@fceller I have same problem with cmake 3.14.3,and reported here https://github.com/arangodb/fuerte/issues/18

**Comment by ghost** [comment]
Same problem when using the terminal:

sandro@debian:~/NetBeansProjects/fuerte/build$ cmake ..       -DCMAKE_BUILD_TYPE=build-release       -DFUERTE_TESTS=On       -DFUERTE_EXAMPLES=ON       -DVELOCYPACK_SOURCE_DIR=/home/sandro/NetBeansProjects/velocypack
CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version 107000
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:1470 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:26 (find_package)


CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version 107000
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:1470 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:26 (find_package)


-- Boost version: 1.70.0
-- Found the following Boost libraries:
--   system
--   thread
-- Build mode: build-release
-- Install base directory: /usr/local
-- Hardware support for SSE4.2 on this machine: true
-- Compiler type CLANG: /usr/bin/clang++
-- Building with SSE 4.2 optimizations enabled: ON
-- Building with hash type: xxhash
-- Building bench performance test suite: OFF
-- Building support programs and tools: ON
-- Building examples: OFF
-- Building test suite: OFF
-- Building large tests: OFF
-- Building assembler test suite: OFF
-- Compiler type UNKNOWN: /usr/bin/clang++
-- copy compile_commands.json
-- Configuring done
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILE_OBJECT
-- Generating done
-- Build files have been written to: /home/sandro/NetBeansProjects/fuerte

But.... - When compiled in NetBeans, I have a different error:

CLEAN SUCCESSFUL (total time: 705ms)
cd '/home/sandro/NetBeansProjects/fuerte'
/usr/bin/make -f Makefile
[  1%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/velocypack-common.cpp.o
[  3%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/AttributeTranslator.cpp.o
[  4%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/Builder.cpp.o
[  6%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/Collection.cpp.o
[  7%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/Dumper.cpp.o
[  9%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/Exception.cpp.o
[ 10%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/HexDump.cpp.o
[ 12%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/Iterator.cpp.o
[ 14%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/Options.cpp.o
[ 15%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/Parser.cpp.o
[ 17%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/Slice.cpp.o
[ 18%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/SliceStaticData.cpp.o
[ 20%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/StringRef.cpp.o
[ 21%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/Utf8Helper.cpp.o
[ 23%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/Validator.cpp.o
[ 25%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/Value.cpp.o
[ 26%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/ValueType.cpp.o
[ 28%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/Version.cpp.o
[ 29%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/asm-functions.cpp.o
[ 31%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/asm-utf8check.cpp.o
[ 32%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/fpconv.cpp.o
[ 34%] Building CXX object vpack-build/CMakeFiles/velocypack.dir/src/xxhash.cpp.o
[ 35%] Linking CXX static library libvelocypack.a
[ 35%] Built target velocypack
[ 37%] Building CXX object CMakeFiles/fuerte.dir/src/connection.cpp.o
[ 39%] Building CXX object CMakeFiles/fuerte.dir/src/ConnectionBuilder.cpp.o
[ 40%] Building CXX object CMakeFiles/fuerte.dir/src/helper.cpp.o
[ 42%] Building CXX object CMakeFiles/fuerte.dir/src/http.cpp.o
[ 43%] Building CXX object CMakeFiles/fuerte.dir/src/HttpConnection.cpp.o
[ 45%] Building CXX object CMakeFiles/fuerte.dir/src/jwt.cpp.o
[ 46%] Building CXX object CMakeFiles/fuerte.dir/src/loop.cpp.o
[ 48%] Building CXX object CMakeFiles/fuerte.dir/src/message.cpp.o
[ 50%] Building CXX object CMakeFiles/fuerte.dir/src/requests.cpp.o
[ 51%] Building CXX object CMakeFiles/fuerte.dir/src/types.cpp.o
[ 53%] Building CXX object CMakeFiles/fuerte.dir/src/vst.cpp.o
[ 54%] Building CXX object CMakeFiles/fuerte.dir/src/VstConnection.cpp.o
[ 56%] Building C object CMakeFiles/fuerte.dir/src/http_parser/http_parser.c.o
[ 57%] Linking CXX static library libfuerte.a
/usr/bin/ar: CMakeFiles/fuerte.dir/src/http_parser/http_parser.c.o: No such file or directory
CMakeFiles/fuerte.dir/build.make:405: recipe for target 'libfuerte.a' failed
make[2]: *** [libfuerte.a] Error 1
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/fuerte.dir/all' failed
make[1]: *** [CMakeFiles/fuerte.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

BUILD FAILED (exit value 2, total time: 1m 4s)


Any clues on how to solve this?



Environment:

Debian 9 Stretch
Clang++-8
Clang-8
CMake 3.7.2
NetBeans IDE 10 - Apache
Java 11.0.1

velocypack compiled successfully and installed successfully.

Thanks in advance,


Hisao Nakaguma

**Comment by AlexLuya** [comment]
So bad interaction with users,It is hard to believe arangodb will survive.
