### ISSUE TITLE
State of the Project

### ISSUE THREAD

**Issue by blastmaster** [arangodb/fuerte#2]
Hi, its me ... again :).
Since I'am really looking forward to find some useful schema-less Database, which I can use from C++, I want to ask how long do you think this driver needs until finished?
Did you have an hint for me how I can help? I looked at the code, which seems not to be production ready yet. What are the milestones for this driver?

**Comment by pluma** [comment]
Hi Sebastian,

thanks for your offer. We're trying to make fuerte become the basis of the native C++ driver as well as an optional dependency for the node driver (so we can benefit from the velocypack performance improvements in JS too). We're hoping to have a finished release very soon.

If you want to get involved with the C++ development you should ask @ObiWahn (e.g. in the #driverdev channel of our Community Slack) but I can't promise there's currently anything you can help him with right now.

**Comment by ObiWahn** [comment]
Hi Sebastian,
for the time being we stick to the old C++ driver that was not developed by me. This driver is the one you will find on the **master** branch. I hope to get some time in the future to develop on the experimental branch. But for the next weeks I have been given other tasks. So I am not able to promise anything. What are your thoughts on the driver? What would you like to see? In what way could you imagine to help? I could do a bit of development in my free time and maybe guide you in case you would like to get your hands dirty.

Regards
Jan

**Comment by fceller** [comment]
@blastmaster as @ObiWahn wrote, we want to do some makeover. I will create a 0.8 branch for the old driver. Please note that it is still experimental.

**Comment by sandrokeil** [comment]
Any new news / plans?

**Comment by pluma** [comment]
Hi @sandrokeil, as you can see from the commit log, there has been quite a bit activity in the meantime thanks to @ewoutp who has taken over and is leading the integration into arangojs. We'll have to release node-arangodb-cxx as a standalone node module first, though.

**Comment by sandrokeil** [comment]
Great, because I'm working on an [ArangoDB PHP Extension](https://github.com/sandrokeil/arangodb-php-driver/) which is based on fuerte/velocypack and looking forward for a stable release. I hope the API will not change so much in the meanwhile.

**Comment by sandrokeil** [comment]
It looks all projects makes progress, except this one. Any Roadmap for 2018? /cc @fceller @ewoutp @ObiWahn

**Comment by graetzer** [comment]
ArangoDB 3.4 uses fuerte for the arangosh implementation. We are targeting 3.5 with the goal of completely replacing the internal cluster communication layer with fuerte.

If we manage to do it way might add http2 support
