### ISSUE TITLE
Documentation request: Explain the role of Velocypack Attribute Translators

### ISSUE THREAD

**Issue by lumieria** [arangodb/fuerte#24]
This code:
std::string key=result->slices().front().get("_key").copyString();
from this page:
https://www.arangodb.com/2017/11/introduction-fuerte-arangodb-c-plus-plus-driver/

Is causing the app to terminate with the following exception:
Cannot execute operation without attribute translator

In looking around, I can't seem to find any indication of how to provide what it is looking for, or otherwise access the value of _key.

Can you provide an example for this?

Thank you!

**Comment by lumieria** [comment]
I guess, better even, would just be to show how one gets the built in attributes, that seem to come back with Null keys (at least in the above-mentioned example):  _key, _id, _rev.  Those seem to be pretty key attributes to be able to access and refer to, but seem to be special-cases?  Any clarity would help.

**Comment by graetzer** [comment]
https://github.com/arangodb/arangodb/blob/680971e81aa858e4c9e4938e4372988cb4d430eb/3rdParty/fuerte/include/fuerte/VpackInit.h

Should be enough to instantiate this in the main

**Comment by lumieria** [comment]
@graetzer... thank you!  That workaround works perfectly.  

For anyone else wondering about the "Why" of it, there's a bit more of a description here where I cross posted the question: [https://github.com/arangodb/velocypack/issues/61](https://github.com/arangodb/velocypack/issues/61)
