### ISSUE TITLE
Bug with Velocystream v1.1

### ISSUE THREAD

**Issue by martin-schilling** [arangodb/fuerte#8]
Hi,
thanks for this awesome project.
While working with fuerte and velocypack I came upon an issue with velocystream. I tried sending this [json.txt](https://github.com/arangodb/fuerte/files/1523844/json.txt) to "/_api/transaction" as a POST request and it works fine with vst1.0 but it fails with vst1.1. Is this a bug or am I doing something wrong?
This is the error message:
```
Operation canceled
terminate called after throwing an instance of 'arangodb::fuerte::v1::ErrorCondition'
```

**Comment by sandrokeil** [comment]
It looks like the request is sent to ArangoDB and the transaction will be initiated (see [logs](https://gist.github.com/sandrokeil/ccb278b8d841bc7b4dd235d986ee0c0c)) but there will be no response.

**Comment by sandrokeil** [comment]
ping @jsteemann

**Comment by dothebart** [comment]
@ewoutp is probably the better person to ping about this.

**Comment by sandrokeil** [comment]
Maybe a missing hint is, that it depends on the size of the payload.

**Comment by graetzer** [comment]
if this is not fixed with the latest version, please reopen the issue
